DROP TABLE IF EXISTS AGENDA_EVENTOS;
DROP TABLE IF EXISTS AGENDA_USUARIOS;
DROP TABLE IF EXISTS AGENDA_CATEGORIAS;
DROP TABLE IF EXISTS AGENDA_ENTIDADES;


CREATE TABLE AGENDA_USUARIOS(
	USUARIO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO VARCHAR(10)  NOT NULL ,
	PASSWORD VARCHAR(10)  NOT NULL ,
    PRIMARY KEY(USUARIO_ID)
);

CREATE TABLE AGENDA_CATEGORIAS(
	CATEGORIA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	CATEGORIA VARCHAR(50)  NOT NULL ,
	PRIMARY KEY(CATEGORIA_ID)
);

CREATE TABLE AGENDA_ENTIDADES(
	ENTIDAD_ID INTEGER NOT NULL AUTO_INCREMENT ,
	ENTIDAD VARCHAR(50)  NOT NULL ,
	PRIMARY KEY(ENTIDAD_ID)
);

CREATE TABLE AGENDA_EVENTOS(
	EVENTO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	EVENTO VARCHAR( 50 ), 	
	ENTIDAD_ID INTEGER,
	CATEGORIA_ID INTEGER,
	UBICACION VARCHAR( 50 ),
	FECHA DATE,
	HORA TIME,
	PRIMARY KEY(EVENTO_ID)
);


ALTER TABLE AGENDA_EVENTOS ADD CONSTRAINT fkagenda_categorias FOREIGN KEY (CATEGORIA_ID) REFERENCES AGENDA_CATEGORIAS( CATEGORIA_ID);
ALTER TABLE AGENDA_EVENTOS ADD CONSTRAINT fkagenda_entidades FOREIGN KEY (ENTIDAD_ID) REFERENCES AGENDA_ENTIDADES( ENTIDAD_ID);
	
INSERT INTO AGENDA_USUARIOS ( USUARIO, PASSWORD ) VALUES ( 'fernando', 'fernando');

INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'DEPORTES');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'TEATRO');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'CONCIERTOS');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'INFANTIL');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'TALLERES');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'FIESTAS');
INSERT INTO AGENDA_CATEGORIAS ( CATEGORIA ) VALUES ( 'EXPOSICIONES');

INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'TEADRO ROMEA');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'TEATRO CIRCO');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'CONSEJERIA EDUCACION');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'AYUNTAMIENTO MURCIA');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'PLAZA DE TOROS');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'SALA REM');
INSERT INTO AGENDA_ENTIDADES ( ENTIDAD ) VALUES ( 'REAL MURCIA');

INSERT INTO AGENDA_EVENTOS ( EVENTO,ENTIDAD_ID, CATEGORIA_ID, UBICACION,FECHA, HORA ) VALUES ( 'Presentacion Libro Ambientes Murcianos',4, 7, 'Sala Veronicas','2017-01-01', '17:00' ); 
INSERT INTO AGENDA_EVENTOS ( EVENTO,ENTIDAD_ID, CATEGORIA_ID, UBICACION,FECHA, HORA ) VALUES ( 'Presentacion Feria Murcia',5, 6, 'Sala Veronicas','2017-01-01', '17:00' ); 
