DROP TABLE IF EXISTS CAU_PARTES;
DROP TABLE IF EXISTS CAU_USUARIOS;
DROP TABLE IF EXISTS CAU_SERVICIOS;

CREATE TABLE CAU_USUARIOS(
	USUARIO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO VARCHAR(10)  NOT NULL ,
	PASSWORD VARCHAR(10)  NOT NULL ,
	PRIMARY KEY (USUARIO_ID)  
);

CREATE TABLE CAU_SERVICIOS(
	SERVICIO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	SERVICIO VARCHAR( 50 )  NOT NULL ,
	PRIMARY KEY(SERVICIO_ID)  
);

CREATE TABLE CAU_PARTES(
	PARTE_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO_ID INTEGER,
	SERVICIO_ID INTEGER,
	TELEFONO VARCHAR( 50 ),
	AVERIA VARCHAR( 50 ),
	UBICACION VARCHAR( 50 ),
	FECHA	DATE,
	PRIMARY KEY(PARTE_ID)
);

ALTER TABLE CAU_PARTES ADD CONSTRAINT fkcau_usuarios FOREIGN KEY (USUARIO_ID) REFERENCES CAU_USUARIOS( USUARIO_ID);
ALTER TABLE CAU_PARTES ADD CONSTRAINT fkcau_servicios FOREIGN KEY (SERVICIO_ID) REFERENCES CAU_SERVICIOS( SERVICIO_ID);
	
INSERT INTO CAU_USUARIOS ( USUARIO, PASSWORD ) VALUES ( 'usuario', 'password');

INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'LABORATORIO');
INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'DIRECCION');
INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'FARMACIA');
INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'REHABILITACION');
INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'CONSULTAS');
INSERT INTO CAU_SERVICIOS ( SERVICIO ) VALUES ( 'URGENCIAS');

