DROP TABLE IF EXISTS POLL_RESULTADOS;
DROP TABLE IF EXISTS POLL_POLLS;
DROP TABLE IF EXISTS POLL_RESPUESTAS;
DROP TABLE IF EXISTS POLL_PREGUNTAS;
DROP TABLE IF EXISTS POLL_ENCUESTAS;

CREATE TABLE POLL_ENCUESTAS (
  ENCUESTA_ID INTEGER NOT NULL AUTO_INCREMENT ,
  ENCUESTA VARCHAR( 100 )NOT NULL,
  PRIMARY KEY(ENCUESTA_ID));

CREATE TABLE POLL_PREGUNTAS (
  PREGUNTA_ID INTEGER NOT NULL AUTO_INCREMENT ,
  ENCUESTA_ID INTEGER NOT NULL  ,
  ORDEN INTEGER NOT NULL  ,
  PREGUNTA VARCHAR( 100 ),
  PRIMARY KEY(PREGUNTA_ID),
  FOREIGN KEY(ENCUESTA_ID) REFERENCES POLL_ENCUESTAS(ENCUESTA_ID));

CREATE TABLE POLL_RESPUESTAS (
  RESPUESTA_ID INTEGER NOT NULL AUTO_INCREMENT ,
  PREGUNTA_ID INTEGER NOT NULL  ,
  ORDEN INTEGER NOT NULL  ,
  RESPUESTA VARCHAR( 100 ),
  PRIMARY KEY(RESPUESTA_ID),
  FOREIGN KEY(PREGUNTA_ID) REFERENCES POLL_PREGUNTAS(PREGUNTA_ID));


CREATE TABLE POLL_POLLS (
  POLL_ID INTEGER NOT NULL AUTO_INCREMENT ,
  IP VARCHAR( 20 ),
  FECHA DATE,
  HORA TIME,
  PRIMARY KEY(POLL_ID));

CREATE TABLE POLL_RESULTADOS (
  RESULTADO_ID INTEGER NOT NULL AUTO_INCREMENT ,
  POLL_ID INTEGER NOT NULL,
  RESPUESTA_ID INTEGER NOT NULL,
  PRIMARY KEY(RESULTADO_ID),
  FOREIGN KEY(POLL_ID) REFERENCES POLL_POLLS( POLL_ID ),
  FOREIGN KEY(RESPUESTA_ID) REFERENCES POLL_RESPUESTAS(RESPUESTA_ID));


INSERT INTO `test`.`POLL_ENCUESTAS` (`ENCUESTA`) VALUES ( 'INTENCION DE VOTACION');
INSERT INTO `test`.`POLL_ENCUESTAS` (`ENCUESTA`) VALUES ( 'VALORACION DE MEDIOS');

INSERT INTO `test`.`POLL_PREGUNTAS` ( `ENCUESTA_ID`, `ORDEN`, `PREGUNTA` ) VALUES ( 1 , 1, 'PARTIDO PREFERIDO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 1 , 1, 'PP'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 1 , 2, 'PSOE'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 1 , 3, 'IU'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 1 , 4, 'NO CONTESTA'); 

INSERT INTO `test`.`POLL_PREGUNTAS` ( `ENCUESTA_ID`, `ORDEN`, `PREGUNTA` ) VALUES ( 1 , 2, 'LIDER PREFERIDO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 2 , 5, 'RAJOY'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 2 , 6, 'SANCHEZ'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 2 , 7, 'GARZON'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 2 , 8, 'NO CONTESTA'); 


INSERT INTO `test`.`POLL_PREGUNTAS` ( `ENCUESTA_ID`, `ORDEN`, `PREGUNTA` ) VALUES ( 2 , 3, 'PERIODICO PREFERIDO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 3 , 9, 'PAIS'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 3 , 10, 'MUNDO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 3 , 11, 'ABC'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 3 , 12, 'LA RAZON'); 

INSERT INTO `test`.`POLL_PREGUNTAS` ( `ENCUESTA_ID`, `ORDEN`, `PREGUNTA` ) VALUES ( 2 , 4, 'RADIO PREFERIDA'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 4 , 13, 'ESRADIO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 4 , 14, 'SER'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 4 , 15, 'ONDACERO'); 
INSERT INTO `test`.`POLL_RESPUESTAS` ( `PREGUNTA_ID`, `ORDEN`, `RESPUESTA` )VALUES ( 4 , 16, 'COPE');