DROP TABLE IF EXISTS NEWSLETTER_BAJA;
DROP TABLE IF EXISTS NEWSLETTER_USUARIOS;

CREATE TABLE NEWSLETTER_USUARIOS(
	USUARIO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO VARCHAR(10)  NOT NULL ,
	EMAIL VARCHAR(50)  NOT NULL ,
    ESTATUS BOOLEAN  NOT NULL,
    PRIMARY KEY(USUARIO_ID)
);

CREATE TABLE NEWSLETTER_BAJA(
	BAJA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO_ID  INTEGER NOT NULL ,
	FECHA DATE,
	HORA TIME,
	PRIMARY KEY(BAJA_ID)
);

ALTER TABLE NEWSLETTER_BAJA ADD CONSTRAINT fkNEWSLETTER_USUARIOAS FOREIGN KEY (USUARIO_ID) REFERENCES NEWSLETTER_USUARIOS( USUARIO_ID);
INSERT INTO NEWSLETTER_USUARIOS ( USUARIO, EMAIL, ESTATUS) VALUES ( 'fernando', 'frm666@gmail.com', TRUE );