DROP TABLE IF EXISTS PARTIDOS;
DROP TABLE IF EXISTS JORNADAS;
DROP TABLE IF EXISTS EQUIPOS;

CREATE TABLE EQUIPOS
	(
	EQUIPO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	EQUIPO VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(EQUIPO_ID)  
	);

CREATE TABLE JORNADAS
	(
	JORNADA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	FECHA DATE ,
	PRIMARY KEY(JORNADA_ID)  
	);
	
CREATE TABLE PARTIDOS
	(
	PARTIDO_ID INTEGER NOT NULL AUTO_INCREMENT,
	JORNADA_ID INTEGER NOT NULL,
	LOCAL_ID INTEGER,
	VISITANTE_ID INTEGER,
	MARCADOR_LOCAL INTEGER NOT NULL DEFAULT 0,
	MARCADOR_VISITANTE INTEGER NOT NULL DEFAULT 0,
	ESTADO CHAR,
	PRIMARY KEY(PARTIDO_ID),
	FOREIGN KEY ( JORNADA_ID ) REFERENCES JORNADAS( JORNADA_ID ),
	FOREIGN KEY ( LOCAL_ID ) REFERENCES EQUIPOS( EQUIPO_ID ),
	FOREIGN KEY ( VISITANTE_ID ) REFERENCES EQUIPOS( EQUIPO_ID ) 
	);
	
INSERT INTO equipos ( EQUIPO) VALUES ( 'MADRID');
INSERT INTO equipos ( EQUIPO) VALUES ( 'BARCELONA');
INSERT INTO equipos ( EQUIPO) VALUES ( 'VALENCIA');
INSERT INTO equipos ( EQUIPO) VALUES ( 'MALAGA');
INSERT INTO equipos ( EQUIPO) VALUES ( 'SEVILLA');
INSERT INTO equipos ( EQUIPO) VALUES ( 'ZARAGOZA');


INSERT INTO jornadas ( FECHA ) VALUES ( "2014-10-10");
INSERT INTO jornadas ( FECHA ) VALUES ( "2014-10-17");


INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '1', '2', '1', '0', 'F');
INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '3', '4', '1', '0', 'F');
INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '5', '6', '1', '0', 'F');

INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '2', '2', '3', '1', '0', 'F');
INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '2', '4', '5', '1', '0', 'F');
INSERT INTO partidos (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '2', '6', '1', '1', '0', 'F');
